---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext50
  labels:
    app: BoundedContext50
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext50
  template:
    metadata:
      labels:
        app: BoundedContext50
    spec:
      containers:
        - name: BoundedContext50
          image: username/BoundedContext50:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext50
  labels:
    app: BoundedContext50
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext50
  template:
    metadata:
      labels:
        app: BoundedContext50
    spec:
      containers:
        - name: BoundedContext50
          image: username/BoundedContext50:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext50
  labels:
    app: BoundedContext50
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext50


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext50
  labels:
    app: BoundedContext50
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext50

